<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Role"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="14.371">
  <properties />
            <testcase name="detailOperator" time="14.371" classname="com.wymall.test.testcases.childOperator.ChildOperatorPage_004_detailOperator_Test">
                <failure type="java.lang.AssertionError"
                  message="超时!! 10 秒之后还没找到元素 [By.xpath: //*[@id=&quot;app&quot;]//button[contains(text(),&apos;确认&apos;)][1]]"
              >
<![CDATA[java.lang.AssertionError: 超时!! 10 秒之后还没找到元素 [By.xpath: //*[@id="app"]//button[contains(text(),'确认')][1]]
  org.testng.Assert.fail(Assert.java:94)
  com.wymall.test.utils.SeleniumUtil.waitForElementToLoad(SeleniumUtil.java:275)
  com.wymall.test.utils.SeleniumUtil.click(SeleniumUtil.java:135)
  com.wymall.test.utils.actions.impl.Click.doAction(Click.java:23)
  com.wymall.test.utils.SuperAction.parseExcel(SuperAction.java:271)
  com.wymall.test.testcases.childOperator.ChildOperatorPage_004_detailOperator_Test.detailOperator(ChildOperatorPage_004_detailOperator_Test.java:8)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
