<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="yrb-PC" name="com.wymall.test.testcases.childOperator.ChildOperatorPage_008_delOperator_Test" tests="1" failures="0" timestamp="4 Aug 2018 03:59:40 GMT" time="4.917" errors="1">
  <testcase name="delOperator" time="4.917" classname="com.wymall.test.testcases.childOperator.ChildOperatorPage_008_delOperator_Test">
    <error type="java.lang.AssertionError" message="期望的文字是 [删除成功] 但是找到了 [系统异常]">
      <![CDATA[java.lang.AssertionError: 期望的文字是 [删除成功] 但是找到了 [系统异常]
	at org.testng.Assert.fail(Assert.java:94)
	at com.wymall.test.utils.SeleniumUtil.isTextCorrect(SeleniumUtil.java:332)
	at com.wymall.test.utils.actions.impl.CheckTipsText.doAction(CheckTipsText.java:23)
	at com.wymall.test.utils.SuperAction.parseExcel(SuperAction.java:271)
	at com.wymall.test.testcases.childOperator.ChildOperatorPage_008_delOperator_Test.delOperator(ChildOperatorPage_008_delOperator_Test.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- delOperator -->
</testsuite> <!-- com.wymall.test.testcases.childOperator.ChildOperatorPage_008_delOperator_Test -->
